#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "SSID"
#define WIFI_PASSWORD "PASSWORD"

#define MQTT_BROKER_HOST "192.168.0.***"
#define MQTT_BROKER_PORT 1883
#define MQTT_CLIENT_ID "node1"

#define MQTT_TELEMETRY_TOPIC "cluster/node1/telemetry"
#define MQTT_CONTROL_TOPIC "cluster/node1/control"

#define SENSOR_PERIOD_MS 100
#define CONTROL_PERIOD_MS 200
#define COMPUTE_PERIOD_MS 500
#define MANAGER_PERIOD_MS 1000

#define SENSOR_QUEUE_LENGTH 16

#define SENSOR_TASK_STACK_SIZE 2048
#define CONTROL_TASK_STACK_SIZE 2048
#define COMPUTE_TASK_STACK_SIZE 2048
#define MANAGER_TASK_STACK_SIZE 3072

#define SENSOR_TASK_PRIORITY 5
#define CONTROL_TASK_PRIORITY 5
#define COMPUTE_TASK_PRIORITY 2
#define MANAGER_TASK_PRIORITY 3

#define DEFAULT_LOAD_FACTOR 1000

#endif
